#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

JS_FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" ":!examples/" | sed 's| |\\ |g')

if [ -n "$JS_FILES" ]; then
	# Fix all selected files
	echo "$JS_FILES" | xargs ./node_modules/.bin/xo --fix

	# Add back the modified files to staging
	echo "$JS_FILES" | xargs git add
fi
